ifeq ($(config),debug)
  TARGET_DIR = Debug
else
  TARGET_DIR = Release
endif

.PHONY: run build gen

build: $(PROJECTS)

run: build
	@echo "[make] Running eclipseeditor ($(config))"
	./bin/$(TARGET_DIR)/eclipseeditor/eclipseeditor

gen:
	@echo "Generating project files..."
	./premake5 --file=premake5.lua gmake
	@grep -q '\-include Makefile.custom' Makefile 2>/dev/null || printf '\n-include Makefile.custom\n' >> Makefile
